language: node_js
node_js:
- node
sudo: required
services:
- docker
branches:
  only: 
    - master
addons:
  ssh_known_hosts: ${DEPLOY_HOST}
before_install:
- openssl aes-256-cbc -K $encrypted_8b4e9d927e1d_key -iv $encrypted_8b4e9d927e1d_iv -in deploy_rsa.enc -out deploy_rsa -d
before_deploy:
- openssl aes-256-cbc -K $encrypted_8b4e9d927e1d_key -iv $encrypted_8b4e9d927e1d_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master