version: '3.1'
services:
  api:
    build: ./packages/api
    command: npm run dev
    restart: always
    volumes:
      - ./packages/api:/usr/packages/api
      - ./shared:/usr/packages/api/src/shared
      - /usr/packages/api/node_modules
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://greenhouse@postgres/greenhouse
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3001
  web:
    build: ./packages/web
    command: npm run dev
    restart: always
    volumes:
      - ./packages/web:/usr/packages/web
      - ./shared:/usr/packages/web/src/shared
      - /usr/packages/web/node_modules
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3000
  postgres:
    image: postgres:9.6.2-alpine
    restart: always
    environment:
      POSTGRES_USER: greenhouse
      POSTGRES_DB: greenhouse
    ports:
      - "5433:5432"
  redis:
    image: redis
    restart: always
  proxy:
    image: nginx:alpine
    restart: always
    ports:
    - "8090:8090"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - api
      - web