version: '3.1'
services:
  api:
    command: npm run dev
    environment:
      NODE_ENV: 'development'
  web:
    command: npm run dev
    environment:
      NODE_ENV: 'development'
  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"