version: '3.1'
services:
  api:
    build: ./packages/api
    command: npm run dev
    volumes:
      - ./packages/api:/usr/src/greenhouse-controller-api
      - /usr/src/greenhouse-controller-api/node_modules
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://greenhouse@postgres/greenhouse
      PORT: 3001
  web:
    build: ./packages/web
    command: npm run dev
    volumes:
      - ./packages/web:/usr/src/greenhouse-controller-web
      - /usr/src/greenhouse-controller-web/node_modules
    environment:
      PORT: 3000
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: greenhouse
      POSTGRES_DB: greenhouse
    ports:
      - "5433:5432"
  redis:
    image: redis
  proxy:
    image: nginx:alpine
    ports:
    - "8090:8090"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - api
      - web