version: '3.1'
services:
  api:
    build: ./packages/api
    command: npm run dev
    restart: always
    volumes:
      - ./packages/api:/usr/packages/api
      - ./shared:/usr/packages/api/src/shared
      - /usr/packages/api/node_modules
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 3001
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: postgres://${POSTGRES_USER}@postgres/${POSTGRES_DB}
      REDIS_HOST: redis
      REDIS_PORT: 6379
  web:
    build: ./packages/web
    command: npm run dev
    restart: always
    volumes:
      - ./packages/web:/usr/packages/web
      - ./shared:/usr/packages/web/src/shared
      - /usr/packages/web/node_modules
    depends_on:
      - redis
    environment:
      PORT: 3000
      NODE_ENV: ${NODE_ENV}
      REDIS_HOST: redis
      REDIS_PORT: 6379
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
  redis:
    image: redis
    restart: always
  proxy:
    image: nginx:alpine
    restart: always
    ports:
    - "${PROXY_PORT}:8090"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - api
      - web